import type { Metadata } from "next";
import localFont from "next/font/local";
import SessionProvider from "../app/providers/SessionProvider";
import "./globals.css";
import { Toaster } from "react-hot-toast";
const inter = localFont({
  src: "./fonts/Inter-VariableFont_opsz,wght.woff2",
  weight: "100 900",
  variable: "--font-inter",
  style: "normal",
});
const nunito = localFont({
  src: "./fonts/Nunito-VariableFont_wght.woff2",
  variable: "--font-nunito",
  weight: "200 900",
  style: "normal",
});

export const metadata: Metadata = {
  title: "Env vault",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${nunito.variable} ${inter.variable} antialiased bg-background`}
      >
        <SessionProvider>
          <Toaster/>
          {children}
          </SessionProvider>
      </body>
    </html>
  );
}
